const actions = {
    ADD_DIGIT_TO_INPUT1: 'ADD_DIGIT_TO_INPUT1',
    ADD_DIGIT_TO_INPUT2: 'ADD_DIGIT_TO_INPUT2',
    UPDATE_OPERATOR: 'UPDATE_OPERATOR',
    ADD_DECIMAL_TO_INPUT1: 'ADD_DECIMAL_TO_INPUT1',
    ADD_DECIMAL_TO_INPUT2: 'ADD_DECIMAL_TO_INPUT2',
    UPDATE_LAST_TYPE: 'UPDATE_LAST_TYPE',
    UPDATE_NEGATIVE_FLAG: 'UPDATE_NEGATIVE_FLAG',
    CALCULATE_ANSWER: 'CALCULATE_ANSWER',
    APPLY_OPERATION_TO_ANSWER: 'APPLY_OPERATION_TO_ANSWER',
    CALCULATE_LAST_OPERATION_ON_ANSWER: 'CALCULATE_LAST_OPERATION_ON_ANSWER',
    CLEAR_INPUT1: 'CLEAR_INPUT1',
    CLEAR_INPUT2: 'CLEAR_INPUT2',
    REMOVE_CHAR_FROM_INPUT1: 'REMOVE_CHAR_FROM_INPUT1',
    REMOVE_CHAR_FROM_INPUT2: 'REMOVE_CHAR_FROM_INPUT2',
    CLEAR_CALCULATOR: 'CLEAR_CALCULATOR',
};

export default actions;
